M48
; DRILL file {KiCad 6.0.4} date Sat 09 Apr 2022 16:34:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-09T16:34:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X164.93Y-153.0
T2
X101.4Y-153.0
X156.6Y-137.0
T0
M30
